# Generated by Django 2.1.7 on 2019-04-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='img',
            field=models.CharField(default='', max_length=300),
        ),
    ]
