# Generated by Django 2.1.7 on 2019-05-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='isLiked',
            field=models.BooleanField(default=False),
        ),
    ]
