# Generated by Django 2.1.7 on 2019-05-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_isliked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='isLiked',
        ),
    ]
